name: Run Slack Integration Tests (Separated Endpoints)

on:
  workflow_dispatch:

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask app in background
        run: |
          nohup python app/main.py > app.log 2>&1 &
          echo "Waiting for server to start..."
          timeout=30
          until curl -s http://localhost:8080/ > /dev/null; do
            sleep 1
            timeout=$((timeout-1))
            if [ $timeout -le 0 ]; then
              echo "Server did not start in time"
              exit 1
            fi
          done
          echo "Server is up"

      - name: Test Morning Post
        run: |
          echo "Triggering /post_morning..."
          curl -X POST http://localhost:8080/post_morning

      - name: Test Hourly Post
        run: |
          echo "Triggering /post_hourly..."
          curl -X POST http://localhost:8080/post_hourly

      - name: Test Evening Post
        run: |
          echo "Triggering /post_evening..."
          curl -X POST http://localhost:8080/post_evening

      - name: Show app.log contents
        run: cat app.log