name: Scheduled Slack Bot Posting

on:
  schedule:
    - cron: "0 0-8 * * 1-5"  # UTC 0～8時 → JST 9～17時（平日）
  workflow_dispatch:

jobs:
  post_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run posting script
        run: python app1.py
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_TEST_CHANNEL: ${{ secrets.SLACK_TEST_CHANNEL }}
