name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 手動実行用トリガーを追加

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Run Slack Integration Test (Separated Endpoints)

        on:
          workflow_dispatch:   # 手動実行用

        jobs:
          integration_test:
            runs-on: ubuntu-latest
            env:
              SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask app in background
        run: |
          nohup python app/main.py > app.log 2>&1 &
          sleep 5  # 待機してサーバーの起動を確認

      - name: Test Morning Post
        run: |
          echo "Triggering /post_morning..."
          curl -X POST http://localhost:8080/post_morning

      - name: Test Hourly Post
        run: |
          echo "Triggering /post_hourly..."
          curl -X POST http://localhost:8080/post_hourly

      - name: Test Evening Post
        run: |
          echo "Triggering /post_evening..."
          curl -X POST http://localhost:8080/post_evening